<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Catálogo de médicos por consultorio de la Torre de Consultorios, entregado
 * por el cliente en formato "Consultorio,Nombre del Médico". Un mismo
 * consultorio puede tener varios médicos (comparten horario) y, tal como
 * viene el archivo original, no se corrigen nombres repetidos/similares
 * (p. ej. variantes de apellido de un mismo consultorio); si hay errores de
 * captura, se corrigen después desde la pantalla de administración.
 */
class ConsultoriosMedicosSeeder extends Seeder
{
    private const DATOS_CSV = <<<'CSV'
319,VIOLETA GRISELDA LUNA GARCIA
105,PAULO CESAR OLVERA HERNANDEZ
212,GASTON DOMINGUEZ SAAVEDRA
309,BERENICE GONZALEZ MENDOZA
315,CARLOS LLALIL HUERTA GARCIA
117,OSCAR SANCHEZ HURTADO
117,ALBERTO TEJERO LANGARICA
203,HUMBERTO URIBE RAMOS
212,ROBERTO SIERRA ASCENCIO
311,JOSE LUIS GUADARRAMA ARASI
410,IRENE DOMINGUEZ MARTINEZ
108,ARMANDO OTERO PEREZ
108,EMMANUEL ESCOBEDO SANCHEZ
108,JUAN ANTONIO OMAÑA TOLEDO
108,ULISES LOYOLA GARCIA
108,ERIK DAMIAN LOPEZ
105,JUAN CARLOS RUIZ AGUILAR
107,GABRIEL ZARATE GARCIA
108,FRANCISCO N ROMERO DURAN
108,JOSE ALFONSO GAMEROS MARTINEZ
108,JOSE LUIS GUTIERREZ VELASCO
108,SALVADOR ISAAC FARAH OSORIO
109,RAFAEL ARROYO BORREGO
109,EDITH HERRERA RODRIGUEZ
109,PEDRO LOPEZ SANABRIA
114,TEODORO ARTURO MENDOZA MARTINEZ
114,GERARDO ANGEL DAVILA JAIMES
115,HUGO DE JESUS BALLESTEROS LOYO
205,JAIME SERRANO MANJARREZ
206,JOSE ANTONIO GONZALEZ MORENO
214,MARIO BETANCOURT ANGELES
215,REFUGIO HORACIO QUASS GUTIERREZ
215,ROBERTO RAFAEL UTRILLA COBOS
217,JUAN ALFONSO QUIROZ GONZALEZ
307,GUILLERMO LOZA Y LOPEZ
416,CARLOS JOSE VELASQUEZ CARRILLO
417,JOSE MAXIMILIANO RAMIREZ CAMBEROS
307,GUILLERMO LOZA HERNANDEZ
218,ISRAEL SALAZAR VIZUET
322,DIEGO ALEJANDRO MORENO IBARRA
322,ALEJANDRA HAY GOMEZ
322,LAURA DE HILARIO AVILES
118,ALMA DE JESUS ROMERO SOTO
204,RUTH AIDEE QUIROZ MEJIA
305,DORA HERMINIA BOJORQUEZ GARCIA
315,MARIELA FLORES VERGARA
405,ANGEL GARCIA DIAZ
312,CORALYS GERMANIA ABREU ROSARIO
314,REGINA CANO SALDAÑA
204,FLOR DE MARIA MONTES DE OCA SALINAS
423,ARACELI HINOJOSA RUIZ
217,ROSA ARMIDA MARTINEZ OCAMPO
310,ALEJANDRO ACUÑA ARELLANO
106,HECTOR ISRAEL GUTIERREZ GUTIERREZ
108,MIGUEL ANGEL NOVAS LEON
109,LETICIA ZARZA DELGADO
119,JOSE ANTONIO APARICIO FABILA
120,MONICA PAULIN ARENAS
120,JAIME ABELARDO PEÑA RIVERA
121,MIGUEL ANTONIO URIBE URIBE
122,YOLANDA TERESITA GARCIA SANDOVAL
122,HECTOR JAVIER RANGEL LATORRE
122,MARTA GARCIA SANDOVAL
206,JULIO FERNANDO MUÑIZ JIMENEZ
209,PAULINA G CASTRO OCAMPO
209,IRLANDO LARA PEREYRA
216,JENIFFER PAMELLA SANTOYO VACIO
219,ANGEL ZISTECATL MEZA
219,ERIKA GABRIELA ALVAREZ SALAZAR
219,CARLOS RODOLFO FERNANDEZ MEJIA
219,DULCE ANDREA BARCENAS SANDOVAL
308,NADIA LIZETH VILLANUEVA GARCIA
317,EVELIN MUCIÑO GARCIA
322,GUSTAVO CRUZ ALARCON
406,JUAN PABLO MANZO MAGAÑA
417,DEBORAH BARBA HERNANDEZ
417,CATALINA VILLA JIMENEZ
423,JUAN EMMANUEL TERRON ARRIAGA
423,CLAUDIA MONSERRAT MOYSEN MARIN
312,IRVING JUAREZ
301,CLAUDIA PATRICIA BARZOLA LUMBRERAS
104,EDUARDO BRAVO LOPEZ
122,THELMA HEBE SOTO ORTEGA
314,PAULINA REYES VAZQUEZ
419,ELSA ELIZABETH CARRILLO LOPEZ
409,ANDRES TORRES FLORES
411,JESUS RAFAEL ORTEGA GONZALEZ
105,MARIO ENRIQUE RAMIREZ MONTIEL
114,NERI ISLAS PALACIOS
115,MARIA DEL CARMEN RENTERIA ARELLANO
117,ARTURO PEREZ BOLDE
210,ROSALIA GARCIA PEÑA
410,JOSE ALBERTO ROJAS JIMENEZ
409,GREESLY MARIA VALBUENA VILLASMIL
409,HILDA NAZARET GUTIERREZ AREVALO
409,MANUEL ALEJANDRO MARROQUIN BARRERA
423,FRIDA PARAMO RIVAS
403,HOPE AND LIFE
404,HOPE AND LIFE
407,HOPE AND LIFE
105,VICENTE GUERRERO SEGOVIA
207,NAYELI ACOSTA GARCIA
207,ISMAEL ANTONIO GOMEZ RUIZ
223,ROBERTO DE JESUS GARCIA AVILES
223,EMMANUEL MISAEL PEDRAZA ROJAS
117,OSCAR GABRIEL JIMENEZ CABRERA
212,JOSUE ROJAS MENDOZA
104,RICARDO ORTEGA VALENCIA
104,RICARDO ADRIAN CORTES MONTERRUBIO
104,JORGE LUIS DIAZ ESPINOZA
202,SALVADOR JOSE LOPEZ ORTEGA
306,PABLO DAVID GUERRERO SUAREZ
412,IVAN SAMANO LOPEZ
412,JORGE ALBERTO MIRANDA BARRERA
412,ALFREDO LOPEZ PARRA
102,AMELIA ELIZABETH MALDONADO ORTIZ
117,LETICIA SALINAS VAZQUEZ
109,FERNANDA GONZALEZ AGUIRRE
114,MARIANA MILLAN LOPEZ
123,ELIZABETH ROMERO FLORES
123,LIDIA RODRIGUEZ CRUZ
203,MARIA GUADALUPE AVELLANEDA BARRAGAN
203,ANALY MENA BOTELLO
223,ANA ROSA MASCAREÑO HERNANDEZ
301,EDITH VALERIO MARMOLEJO
312,SANDRA IVETTE MORENO ARCHUNDIA
312,ALICIA FLORES LOVERA
322,FABIOLA MARIA JIMENEZ MARQUEZ
411,INDRA HUERTA MENEZ
416,CAROLINA VELASQUEZ AGUILAR
211,NORMA ANGELICA ANGELES VAZQUEZ
221,NINA GARDUÑO CHAVEZ
221,GRISELDA GARAY PERDOMO
318,JESSICA MARIBEL GARCIA MEJIA
320,JESUS GONZALEZ ARIAS
320,MAYRA DIANA GARCIA MORAN
110,PRISCILA DEL CARMEN PEREZ PEÑALOZA
222,SILVIA FABIOLA SANTA FE DUEÑAS
121,OMAR DE LEON PACHECO
206,LEVY GUZMAN ARANDA
308,MARIO A VALDES CAMPUZANO
204,SARIAAD EDUARDO ORTIZ ARENAS
211,CARLOS ALBERTO RODRIGUEZ CARRASCO
214,JOSEFINA ZENDEJAS IBARRA
417,JESUS HERNANDEZ ALVAREZ
101,RAYMUNDO LECHUGA GUTIERREZ
104,RENATO EDGARDO MENENDEZ FLORES
104,E.MANOLO ALARCON DE LA LUZ
104,MIGUEL ANGEL ROSAS CONTRERAS
105,MARIANA JAIMEZ GARCIA
112,RUBEN CUEVAS VALDES
112,MOISES RUIZ VILLEGAS
121,MARCO ANTONIO ZEPEDA SANTANA
121,BRAULIO ISAAC PALMA SALDIVAR
121,GABRIELA PALOMA MORLAN LOPEZ
201,RAUL AGUILAR LOPEZ
202,ROBERTO GOMEZ RAYGOZA
207,MIGUEL ALBERTO CELIS IVENS
208,CINTHYA YANNET ARZOLA GONZALEZ
208,VERONICA CAAMAL JIMENEZ
208,JAQUELINE HERNANDEZ LOPEZ
208,NORMA DEYANIRA LOPEZ LARA
208,ITZAMARA MEJIA GONZALEZ
210,JAIME ARANGO AGUILAR
302,KARINA ROJAS MARTINEZ
302,AXEL GONZALEZ LOPEZ
302,MARTHA ALICIA DEL VILLAR VILCHIS
302,VICTOR MANUEL BARAJAS VALENCIA
302,ALEJANDRO ROJAS ANDREWS
302,DANITZYAH MEJIA TORRES
302,ROSARIO MARTINEZ RAMIREZ
303,SALVADOR GONZALEZ VARGAS
304,BARUC GOMEZ HERNANDEZ
304,MANUEL IVAN RODRIGUEZ AGUIRRE
305,CECILIA RODRIGUEZ MUÑIZ
307,PAULINA OCAMPO NAJERA
310,DIANA GAMERO GARCIA
312,YESSENIA GARCIA GOMEZ
318,VIOLETA CONTRERAS GARDUÑO
411,MONICA LOPEZ PALAFOX
115,LEOBI CRUZ MONROY
121,CRISTINA AMERICA MEJIAS COLMENARES
312,NUBIA GOMEZ ARGUETA
410,SEBASTIAN ROJAS NORIEGA
115,MARISOL CRUZ GARCIA
115,EULISES OSWALD GARCIA GARCIA
204,MAYRA PAULINA GARCIA MATA
310,MARIA FERNANDA HERNANDEZ CABRERA
117,MARCO ANTONIO SILVA MEDINA
117,ROSA MARIA MIRANDA VEGA
409,VICTOR HUGO CERVANTES LOPEZ
105,DIANA VILLANUEVA
101,CLAUDIO ANDRES MARTINEZ NAVARRO
101,JOSE EDUARDO FLORES NARANJO
102,LUIS MIGUEL FARFAN GARCIA
102,JULIO CARLOS VELEZ DE LA CHICA
103,ELOY ISRAEL OCAÑA RIVERA
103,ABRAHAM LOPEZ FRAZCO
103,ISRAEL LOPEZ MONGE
103,JOSE DANIEL HERNANDEZ CONTRERAS
116,ADRIAN AZIZ CORTES DE LA FUENTE
116,FERNANDO MARTINEZ ZUÑIGA
116,OCTAVIO MARTINEZ MONTIEL
207,JOSE EMMANUEL VARGAS JASSO
207,DAVID CAMPOS PACHECO
207,LUIS BERNARDO HERNANDEZ HERNANDEZ
214,GUSTAVO ADOLFO ZUNIGA MUÑOZ
214,YAJAN KARIN FADUL TRUJILLO
310,EUGENIO ARTURO JAIME LEON
412,DIANA CAÑAS ALCOCER
412,JUAN CARLOS ALVAREZ MICHEL
420,ALFREDO ORTIZ MUCIÑO
108,E OMAR PIÑON SOLIS
111,LAZARO FLORES PEREZ
120,OMAR MORALES ORDAZ
205,JOSE JUAN GUADALUPE ARIAS PATIÑO
210,ANDRES GABRIEL SALAS CONTRERAS
210,ANDRES GABRIEL SALAS GARCIA
214,MARCO ANTONIO ARAGON CASTRO
223,JORGE A TELLEZ DIAZ TRUJILLO
305,JOSUE RAMON ORTIZ ROMERO
305,JUAN FRANCISCO MORALES ROGEL
319,ELI JALIL CAMILO MARTINEZ
416,CARLOS JOSE VELASQUEZ AGUILAR
422,GABRIEL FERNANDO GONZALEZ RUIZ
423,BENJAMIN E MONTAÑO ROCA
111,ALEJANDRO GUTIERREZ TOXQUI
CSV;

    public function run(): void
    {
        $this->importar();
    }

    public function importar(): int
    {
        $filas = collect(explode("\n", trim(self::DATOS_CSV)))
            ->map(fn ($linea) => array_map('trim', explode(',', $linea, 2)))
            ->filter(fn ($par) => count($par) === 2 && $par[0] !== '' && $par[1] !== '');

        foreach ($filas as [$consultorio, $nombreMedico]) {
            DB::table('consultorios_medicos')->updateOrInsert(
                ['consultorio' => $consultorio, 'nombre_medico' => $nombreMedico],
                ['updated_at' => now(), 'created_at' => now()]
            );
        }

        return $filas->count();
    }
}
